font_family	FantasqueSansM Nerd Font Mono Bold
font_size	16.0

background_opacity 0.45
window_padding_width 12

background	#000000
foreground	#e0e0e0

color0 #1a1a1a
color1 #ff5555
color2 #ff5555
color3 #f1fa8c
color4 #e0e0e0
color5 #ff79c6
color6 #8be9fd
color7 #f8f8f2
color8 #44475a
color9 #ff6e6e
color10 #69ff94
color11 #ffffa5
color12 #d6acff
color13 #ff92df
color14 #a4ffff
color15 #ffffff

hide_windows_decorations yes

enable_audio_bell no
